/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Publicidad7
 */
public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmb_0 = new javax.swing.JMenu();
        sta_0 = new javax.swing.JMenu();
        cali_0 = new javax.swing.JMenu();
        ame_0 = new javax.swing.JMenu();
        huila_0 = new javax.swing.JMenu();
        jmb_1 = new javax.swing.JMenu();
        sta_1 = new javax.swing.JMenu();
        cali_1 = new javax.swing.JMenu();
        ame_1 = new javax.swing.JMenu();
        huila_1 = new javax.swing.JMenu();
        jmb_2 = new javax.swing.JMenu();
        sta_2 = new javax.swing.JMenu();
        cali_2 = new javax.swing.JMenu();
        ame_2 = new javax.swing.JMenu();
        huila_2 = new javax.swing.JMenu();
        jmb_3 = new javax.swing.JMenu();
        sta_3 = new javax.swing.JMenu();
        cali_3 = new javax.swing.JMenu();
        ame_3 = new javax.swing.JMenu();
        huila_3 = new javax.swing.JMenu();
        equipos_5 = new javax.swing.JMenu();
        sta_4 = new javax.swing.JMenu();
        cali_4 = new javax.swing.JMenu();
        ame_4 = new javax.swing.JMenu();
        huila_4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 181, 230));

        jPanel1.setBackground(new java.awt.Color(51, 181, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liga Bet Play Femenina – Conmebol Libertadores (2018) Estadísticas Rendimiento Técnico/Táctico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 204, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setName(""); // NOI18N

        jmb_0.setText("2020");

        sta_0.setText("Santa fe");
        jmb_0.add(sta_0);

        cali_0.setText("Dep. Cali");
        jmb_0.add(cali_0);

        ame_0.setText("America");
        jmb_0.add(ame_0);

        huila_0.setText("Huila");
        jmb_0.add(huila_0);

        jMenuBar1.add(jmb_0);

        jmb_1.setText("2021");

        sta_1.setText("Santa fe");
        jmb_1.add(sta_1);

        cali_1.setText("Dep. Cali");
        jmb_1.add(cali_1);

        ame_1.setText("America");
        jmb_1.add(ame_1);

        huila_1.setText("Huila");
        jmb_1.add(huila_1);

        jMenuBar1.add(jmb_1);

        jmb_2.setText("2022");

        sta_2.setText("Santa fe");
        jmb_2.add(sta_2);

        cali_2.setText("Dep. Cali");
        jmb_2.add(cali_2);

        ame_2.setText("America");
        jmb_2.add(ame_2);

        huila_2.setText("Huila");
        jmb_2.add(huila_2);

        jMenuBar1.add(jmb_2);

        jmb_3.setText("2023");

        sta_3.setText("Santa fe");
        jmb_3.add(sta_3);

        cali_3.setText("Dep. Cali");
        jmb_3.add(cali_3);

        ame_3.setText("America");
        jmb_3.add(ame_3);

        huila_3.setText("Huila");
        jmb_3.add(huila_3);

        jMenuBar1.add(jmb_3);

        equipos_5.setText("Equipos");

        sta_4.setText("Santa fe");
        sta_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sta_4ActionPerformed(evt);
            }
        });
        equipos_5.add(sta_4);

        cali_4.setText("Dep. Cali");
        equipos_5.add(cali_4);

        ame_4.setText("America");
        equipos_5.add(ame_4);

        huila_4.setText("Huila");
        equipos_5.add(huila_4);

        jMenuBar1.add(equipos_5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón para salir
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        dispose();
        System.exit(0);

    }//GEN-LAST:event_btnSalirActionPerformed

    private void sta_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sta_4ActionPerformed
        
    }//GEN-LAST:event_sta_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ame_0;
    private javax.swing.JMenu ame_1;
    private javax.swing.JMenu ame_2;
    private javax.swing.JMenu ame_3;
    private javax.swing.JMenu ame_4;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu cali_0;
    private javax.swing.JMenu cali_1;
    private javax.swing.JMenu cali_2;
    private javax.swing.JMenu cali_3;
    private javax.swing.JMenu cali_4;
    private javax.swing.JMenu equipos_5;
    private javax.swing.JMenu huila_0;
    private javax.swing.JMenu huila_1;
    private javax.swing.JMenu huila_2;
    private javax.swing.JMenu huila_3;
    private javax.swing.JMenu huila_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu jmb_0;
    private javax.swing.JMenu jmb_1;
    private javax.swing.JMenu jmb_2;
    private javax.swing.JMenu jmb_3;
    private javax.swing.JMenu sta_0;
    private javax.swing.JMenu sta_1;
    private javax.swing.JMenu sta_2;
    private javax.swing.JMenu sta_3;
    private javax.swing.JMenu sta_4;
    // End of variables declaration//GEN-END:variables
}
